spring:
  datasource:
    generate-unique-name: false
    name: diary
    url: jdbc:h2:mem:diary
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect