spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

logging:
  level:
    root: INFO

server:
  port: 8081
  servlet:
    context-path: /api

app:
  description: Diary API
  version: 1.0

springdoc:
  api-docs:
    path: /api-docs


